spring:
  redis:
    host: 192.168.1.4
    port: 6379
    database: 0
    # Redis数据库索引 默认为0
    lettuce:
      pool:
        # 连接池最大连接数（负值为无限制）
        max-active: 8
        # 连接池最大阻塞时间（负值为无限制）
        max-wait: -1ms
        # 连接池最大空闲连接
        max-idle: 8
        # 连接池最小空闲连接
        min-idle: 1
    timeout: PT10S